### ISSUE TITLE
change layout based on Olena's feedback

### ISSUE THREAD

**Issue by alekslovestech** [alekslovestech/chromatic-circle#104]
- [ ] Portrait mode 
    - [x] staff on top
    - [x] settings in the middle #102 
    - [x] Circular next #103 
    - [x] Linear at the bottom
- [ ] Landscape mode
    - [x] Circular top-left #103
    - [x] Linear bottom-left
    - [x] Staff top-right
    - [ ] Settings bottom right #102

Also depends on #105
